version: '2.1'
services:
  arbitrage-one-chain-bot:
    build:
      context: .
      dockerfile: one_chain/Dockerfile
    volumes:
      - ./logs/one_chain:/app/logs/one_chain
    restart: always
    env_file:
      - config.env
    networks:
      - mevbot_project_net
  arbitrage-some-chains-bot:
    build:
      context: .
      dockerfile: multi_chain/Dockerfile
    volumes:
      - ./logs/multi_chain:/app/logs/multi_chain
    restart: always
    env_file:
      - config.env
    networks:
      - mevbot_project_net
networks:
  mevbot_project_net:



# sudo docker-compose build
# sudo docker-compose up
# sudo docker-compose down
# sudo docker-compose rm -f $(sudo docker-compose ps -a -q)