"""add ABIs table

Revision ID: 9fa5db64ec00
Revises: 
Create Date: 2024-07-11 14:21:22.860095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa5db64ec00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('net', sa.String(), nullable=True),
    sa.Column('abi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abis_name'), 'abis', ['name'], unique=False)
    op.create_index(op.f('ix_abis_net'), 'abis', ['net'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abis_net'), table_name='abis')
    op.drop_index(op.f('ix_abis_name'), table_name='abis')
    op.drop_table('abis')
    # ### end Alembic commands ###
